spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dhdlsrnr1232?serverTimezone=Asia/Seoul
    username: dhdlsrnr1232
    password: dlsrnr12!
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    cache: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
